defaults:
  - dataset: easy

model_id: nq
mode: eval
cuda:
per_gpu_train_batch_size: 8
learning_rate: 5e-5
adam_epsilon: 1e-8
weight_decay: 0.0
num_train_epochs: 3
max_sequence_length: 4096
doc_stride: 2048
max_query_length: 36
logging_steps: 20
max_grad_norm: 1.0
model_path:
n_gpu: